# Generated by Django 5.2.8 on 2025-11-15 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payslip_text', models.TextField(blank=True, help_text='Extracted text from payslip')),
                ('payslip_image', models.ImageField(blank=True, null=True, upload_to='payslip_images/')),
                ('employee_name', models.CharField(blank=True, max_length=255)),
                ('employee_id', models.CharField(blank=True, max_length=100)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('loan_suggestion', models.TextField(blank=True, help_text='AI-generated loan suggestion')),
                ('loan_available', models.BooleanField(default=False)),
                ('loan_type', models.CharField(blank=True, max_length=255)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Annual interest rate in percentage', max_digits=5, null=True)),
                ('max_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_term_months', models.IntegerField(blank=True, help_text='Loan term in months', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Green Loan Application',
                'verbose_name_plural': 'Green Loan Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
