# Generated by Django 5.2.8 on 2025-11-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenaudit',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='greenaudit',
            name='bill_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='greenaudit',
            name='billing_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='greenaudit',
            name='current_reading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='greenaudit',
            name='energy_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='greenaudit',
            name='kwh_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total kWh consumed', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='greenaudit',
            name='previous_reading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='greenaudit',
            name='supply_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='greenaudit',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total bill amount in MUR', max_digits=10, null=True),
        ),
    ]
