# Generated by Django 5.2.8 on 2025-11-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VATReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("business_id", models.CharField(max_length=255)),
                ("vat_collected", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vat_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reporting_period", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("encrypted_message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
