# Generated by Django 5.2.8 on 2025-11-15 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_exchange", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="image",
        ),
        migrations.CreateModel(
            name="BusinessImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="business_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="waste_exchange.business",
                    ),
                ),
            ],
        ),
    ]
